package nl.hsac.fitnesse.util;

/**
 * Enum of Dutch BIC codes
 */
public enum NlBankCodes {
    ABNA, // ABN AMRO BANK
    FTSB, // ABN AMRO BANK (ex FORTIS BANK)
    AEGO, // AEGON BANK
    ANAA, // ALLIANZ NEDERLAND ASSET MANAGEMENT
    ANDL, // ANADOLUBANK
    ARBN, // ACHMEA BANK
    ARSN, // ARGENTA SPAARBANK
    ARTE, // GE ARTESIA BANK
    ASNB, // ASN BANK
    ASRB, // ASR BANK
    ATBA, // AMSTERDAM TRADE BANK
    BBRU, // ING BELGIE, BREDA
    BCDM, // BANQUE CHAABI DU MAROC
    BCIT, // INTESA SANPAOLO
    BICK, // BINCKBANK
    BKCH, // BANK OF CHINA
    BKMG, // BANK MENDES GANS
    BLGW, // BLG WONEN
    BMEU, // BMCE EUROSERVICES
    BNGH, // BANK NEDERLANDSE GEMEENTEN
    BNPA, // BNP PARIBAS
    BOFA, // BANK OF AMERICA
    BOFS, // BANK OF SCOTLAND, AMSTERDAM
    BOTK, // BANK OF TOKYO-MITSUBISHI UFJ
    CHAS, // JPMORGAN CHASE
    CITC, // CITCO BANK
    CITI, // CITIBANK INTERNATIONAL
    COBA, // COMMERZBANK
    DEUT, // DEUTSCHE BANK (bij alle SEPA transacties)
    DHBN, // DEMIR-HALK BANK
    DLBK, // DELTA LLOYD BANK
    DNIB, // NIBC BANK
    FBHL, // CREDIT EUROPE BANK
    FLOR, // DE NEDERLANDSCHE BANK
    FRBK, // FRIESLAND BANK
    FRGH, // FGH BANK
    FVLB, // F. VAN LANSCHOT BANKIERS
    GILL, // THEODOOR GILISSEN
    HAND, // SVENSKA HANDELSBANKEN
    HHBA, // HOF HOORNEMAN BANKIERS
    HSBC, // HSBC BANK
    ICBK, // INDUSTRIAL & COMMERCIAL BANK OF CHINA
    INGB, // ING BANK
    INSI, // INSINGER DE BEAUFORT
    ISBK, // ISBANK
    KABA, // YAPI KREDI BANK
    KASA, // KAS BANK
    KNAB, // KNAB
    KOEX, // KOREA EXCHANGE BANK
    KRED, // KBC BANK
    LOCY, // LOMBARD ODIER DARIER HENTSCH & CIE
    LOYD, // LLOYDS TSB BANK
    LPLN, // LEASEPLAN CORPORATION
    MHCB, // MIZUHO CORPORATE BANK
    NNBA, // NATIONALE-NEDERLANDEN BANK
    NWAB, // NEDERLANDSE WATERSCHAPSBANK
    OVBN, // LEVOB BANK
    RABO, // RABOBANK
    RBOS, // ROYAL BANK OF SCOTLAND
    RBRB, // REGIOBANK
    SNSB, // SNS BANK
    SOGE, // SOCIETE GENERALE
    STAL, // STAALBANKIERS
    TEBU, // THE ECONOMY BANK
    TRIO, // TRIODOS BANK
    UBSW, // UBS BANK
    UGBI, // GARANTIBANK INTERNATIONAL
    VOWA, // VOLKSWAGEN BANK
    ZWLB  // ZWITSERLEVENBANK
}
