package nl.hsac.fitnesse.util.iban;

public class CYIbanGenerator extends IbanGenerator {

    /**
     * Generates random number to create IBAN.
     *
     * @return random IBAN.
     */

    public String generateIban(String bankCode) {

        String countryCode = "CY";
        int accountLength = 16;
        String accountCodeType = "N";
        int bankCodeLength = 8;
        String bankCodeType = "N";

        bankCode = getBankCode(bankCode, BANK_CODE_LIST, bankCodeLength, bankCodeType);
        String account = getAccount(accountLength, accountCodeType);
        String controlNr = getControlNumber(bankCode, account, countryCode);

        return countryCode + controlNr + bankCode + account;

    }

    public final static String[] BANK_CODE_LIST = {
            "00100001",    //CENTRAL BANK OF CYPRUS HEAD OFFICE
            "00200101",    //BANK OF CYPRUS PUBLIC COMPANY LTD TREASURY ACCOUNTING DEPT.
            "00200102",    //BANK OF CYPRUS PUBLIC COMPANY LTD CLEARING
            "00200104",    //BANK OF CYPRUS PUBLIC COMPANY LTD BANK CARD CENTRE
            "00200106",    //BANK OF CYPRUS PUBLIC COMPANY LTD DASOUPOLIS
            "00200107",    //BANK OF CYPRUS PUBLIC COMPANY LTD AGLANJIA
            "00200108",    //BANK OF CYPRUS PUBLIC COMPANY LTD EVROU
            "00200109",    //BANK OF CYPRUS PUBLIC COMPANY LTD LATSIA
            "00200110",    //BANK OF CYPRUS PUBLIC COMPANY LTD NICOSIA MAIN BRANCH
            "00200111",    //BANK OF CYPRUS PUBLIC COMPANY LTD METOCHIOU KYKKOU
            "00200112",    //BANK OF CYPRUS PUBLIC COMPANY LTD STASSINOU
            "00200113",    //BANK OF CYPRUS PUBLIC COMPANY LTD ARCH.MAKARIOU
            "00200114",    //BANK OF CYPRUS PUBLIC COMPANY LTD NAVARINOU
            "00200115",    //BANK OF CYPRUS PUBLIC COMPANY LTD KANTARAS
            "00200116",    //BANK OF CYPRUS PUBLIC COMPANY LTD PRIVATE BANKING WEST NICOSIA
            "00200117",    //BANK OF CYPRUS PUBLIC COMPANY LTD STAVROU
            "00200118",    //BANK OF CYPRUS PUBLIC COMPANY LTD DEM. SEVERI
            "00200119",    //BANK OF CYPRUS PUBLIC COMPANY LTD DALI
            "00200120",    //BANK OF CYPRUS PUBLIC COMPANY LTD DIAGOROU
            "00200121",    //BANK OF CYPRUS PUBLIC COMPANY LTD KAKOPETRIA
            "00200122",    //BANK OF CYPRUS PUBLIC COMPANY LTD BUSINESS CENTRE EVROU
            "00200123",    //BANK OF CYPRUS PUBLIC COMPANY LTD ELEFTHERIA SQUARE
            "00200124",    //BANK OF CYPRUS PUBLIC COMPANY LTD KYR. MATSIS
            "00200125",    //BANK OF CYPRUS PUBLIC COMPANY LTD ACROPOLIS
            "00200126",    //BANK OF CYPRUS PUBLIC COMPANY LTD ALPHAMEGA BRANCH
            "00200127",    //BANK OF CYPRUS PUBLIC COMPANY LTD STROVOLOU
            "00200128",    //BANK OF CYPRUS PUBLIC COMPANY LTD SPYROU KYPRIANOU
            "00200129",    //BANK OF CYPRUS PUBLIC COMPANY LTD PALIOMETOCHO
            "00200130",    //BANK OF CYPRUS PUBLIC COMPANY LTD EVAGOROU
            "00200131",    //BANK OF CYPRUS PUBLIC COMPANY LTD SUPERMARKET ATHIENITIS CASH OFFICE
            "00200132",    //BANK OF CYPRUS PUBLIC COMPANY LTD BUSINESS CENTRE METOCHIOU KYKKOU
            "00200133",    //BANK OF CYPRUS PUBLIC COMPANY LTD BUSINESS CENTRE LATSION
            "00200134",    //BANK OF CYPRUS PUBLIC COMPANY LTD TSERI
            "00200135",    //BANK OF CYPRUS PUBLIC COMPANY LTD PRIVATE BANKING EAST NICOSIA
            "00200136",    //BANK OF CYPRUS PUBLIC COMPANY LTD PRODROMOU
            "00200137",    //BANK OF CYPRUS PUBLIC COMPANY LTD AKAKI
            "00200138",    //BANK OF CYPRUS PUBLIC COMPANY LTD GREGORI AFXENTIOU
            "00200139",    //BANK OF CYPRUS PUBLIC COMPANY LTD PERISTERONA -CASH OFFICE
            "00200140",    //BANK OF CYPRUS PUBLIC COMPANY LTD MAKEDONITISSA
            "00200141",    //BANK OF CYPRUS PUBLIC COMPANY LTD AGROS
            "00200142",    //BANK OF CYPRUS PUBLIC COMPANY LTD BUSINESS CENTRE ARCH.MAKARIOU
            "00200143",    //BANK OF CYPRUS PUBLIC COMPANY LTD INTERNATIONAL DIVISION
            "00200144",    //BANK OF CYPRUS PUBLIC COMPANY LTD YERIOU
            "00200145",    //BANK OF CYPRUS PUBLIC COMPANY LTD PALECHORI
            "00200146",    //BANK OF CYPRUS PUBLIC COMPANY LTD LYTHRODONTAS
            "00200147",    //BANK OF CYPRUS PUBLIC COMPANY LTD DEFTERA
            "00200148",    //BANK OF CYPRUS PUBLIC COMPANY LTD KATO LAKATAMIA
            "00200149",    //BANK OF CYPRUS PUBLIC COMPANY LTD ANTHOUPOLI
            "00200150",    //BANK OF CYPRUS PUBLIC COMPANY LTD AYIOS PAVLOS
            "00200151",    //BANK OF CYPRUS PUBLIC COMPANY LTD BUSINESS CENTRE DIAGOROU
            "00200152",    //BANK OF CYPRUS PUBLIC COMPANY LTD EVRYCHOU
            "00200153",    //BANK OF CYPRUS PUBLIC COMPANY LTD AY. VARVARA
            "00200154",    //BANK OF CYPRUS PUBLIC COMPANY LTD AYIOS ELEFTHERIOS
            "00200155",    //BANK OF CYPRUS PUBLIC COMPANY LTD INTERNATIONAL BUSINESS UNIT
            "00200156",    //BANK OF CYPRUS PUBLIC COMPANY LTD CREDIT CONTROL HEADOFFICE
            "00200157",    //BANK OF CYPRUS PUBLIC COMPANY LTD CAPITAL CENTRE
            "00200158",    //BANK OF CYPRUS PUBLIC COMPANY LTD IOSIF CHR. H''IOSIF AVE
            "00200159",    //BANK OF CYPRUS PUBLIC COMPANY LTD PERA CHORIO NISSOU
            "00200160",    //BANK OF CYPRUS PUBLIC COMPANY LTD KALOPANAYIOTIS - CASH OFFICE
            "00200161",    //BANK OF CYPRUS PUBLIC COMPANY LTD THE MALL BRANCH
            "00200162",    //BANK OF CYPRUS PUBLIC COMPANY LTD XENIOS COURT
            "00200163",    //BANK OF CYPRUS PUBLIC COMPANY LTD TSERIOU AV.
            "00200164",    //BANK OF CYPRUS PUBLIC COMPANY LTD LYKAVITOS AVE
            "00200165",    //BANK OF CYPRUS PUBLIC COMPANY LTD BUSINESS CENTRE STROVOLOS AVE.
            "00200166",    //BANK OF CYPRUS PUBLIC COMPANY LTD ATHALASSAS AVE-CASH OFFICE
            "00200167",    //BANK OF CYPRUS PUBLIC COMPANY LTD KYPEROUNTA-CASH OFFICE
            "00200168",    //BANK OF CYPRUS PUBLIC COMPANY LTD PEDOULAS-CASH OFFICE
            "00200169",    //BANK OF CYPRUS PUBLIC COMPANY LTD PRODROMOS-CASH OFFICE
            "00200170",    //BANK OF CYPRUS PUBLIC COMPANY LTD HEAD OFFICE’S CASH OFFICE
            "00200172",    //BANK OF CYPRUS PUBLIC COMPANY LTD BUSINESS CENTRE STASSINOS AVE.
            "00200173",    //BANK OF CYPRUS PUBLIC COMPANY LTD AY.ANTONIOS
            "00200174",    //BANK OF CYPRUS PUBLIC COMPANY LTD AY.OMOLOYITAE
            "00200175",    //BANK OF CYPRUS PUBLIC COMPANY LTD KENNEDY AV.
            "00200176",    //BANK OF CYPRUS PUBLIC COMPANY LTD KAIMAKLI
            "00200177",    //BANK OF CYPRUS PUBLIC COMPANY LTD PANO LAKATAMIA
            "00200178",    //BANK OF CYPRUS PUBLIC COMPANY LTD ASTROMERITIS
            "00200179",    //BANK OF CYPRUS PUBLIC COMPANY LTD KOKKINOTRIMITHIA
            "00200181",    //BANK OF CYPRUS PUBLIC COMPANY LTD CORPORATE BANKING CENTRE N/SIA 1
            "00200182",    //BANK OF CYPRUS PUBLIC COMPANY LTD CORPORATE BANKING CENTRE N/SIA 2
            "00200183",    //BANK OF CYPRUS PUBLIC COMPANY LTD CORPORATE BANKING CENTRE H.O.1
            "00200184",    //BANK OF CYPRUS PUBLIC COMPANY LTD RECOVERIES L/SIA & ORGANISMOS
            "00200186",    //BANK OF CYPRUS PUBLIC COMPANY LTD PLATY AGLANTZIAS
            "00200187",    //BANK OF CYPRUS PUBLIC COMPANY LTD CBC 3 , HEADOFFICE
            "00200189",    //BANK OF CYPRUS PUBLIC COMPANY LTD CORPORATE BANKING CENTRE H.O.2
            "00200190",    //BANK OF CYPRUS PUBLIC COMPANY LTD LEASING
            "00200193",    //BANK OF CYPRUS PUBLIC COMPANY LTD NICOSIA TRADE FINANCE CENTRE
            "00200194",    //BANK OF CYPRUS PUBLIC COMPANY LTD CORPORATE BANKING CENTRE N/SIA 4
            "00200195",    //BANK OF CYPRUS PUBLIC COMPANY LTD DIRECT BANKING
            "00200198",    //BANK OF CYPRUS PUBLIC COMPANY LTD CORPORATE SERVICE CENTRE NICOSIA
            "00200199",    //BANK OF CYPRUS PUBLIC COMPANY LTD CORPORATE BANKING CENTRE N/SIA 3
            "00200291",    //BANK OF CYPRUS PUBLIC COMPANY LTD RUSSIAN BANKING CENTRE
            "00200292",    //BANK OF CYPRUS PUBLIC COMPANY LTD ROMANIAN BANKING CENTRE
            "00200295",    //BANK OF CYPRUS PUBLIC COMPANY LTD UKRAINE BANKING CENTRE
            "00200316",    //BANK OF CYPRUS PUBLIC COMPANY LTD PRIVATE BANKING LIMASSOL
            "00200330",    //BANK OF CYPRUS PUBLIC COMPANY LTD LIMASSOL MAIN BRANCH
            "00200331",    //BANK OF CYPRUS PUBLIC COMPANY LTD ARCH.MAKARIOS (AVE)
            "00200332",    //BANK OF CYPRUS PUBLIC COMPANY LTD KAPSALOS
            "00200333",    //BANK OF CYPRUS PUBLIC COMPANY LTD LINOPETRA
            "00200334",    //BANK OF CYPRUS PUBLIC COMPANY LTD PAPHOS STR
            "00200335",    //BANK OF CYPRUS PUBLIC COMPANY LTD PENTADROMOS
            "00200336",    //BANK OF CYPRUS PUBLIC COMPANY LTD OMONIAS
            "00200337",    //BANK OF CYPRUS PUBLIC COMPANY LTD 28TH OCTOBER
            "00200338",    //BANK OF CYPRUS PUBLIC COMPANY LTD POTAMOS YERMASOYIAS
            "00200339",    //BANK OF CYPRUS PUBLIC COMPANY LTD MESA YITONIA
            "00200341",    //BANK OF CYPRUS PUBLIC COMPANY LTD AYIOS IOANNIS
            "00200342",    //BANK OF CYPRUS PUBLIC COMPANY LTD EFTAPATO
            "00200343",    //BANK OF CYPRUS PUBLIC COMPANY LTD KATHOLIKI
            "00200344",    //BANK OF CYPRUS PUBLIC COMPANY LTD ELEFTHERIAS
            "00200345",    //BANK OF CYPRUS PUBLIC COMPANY LTD FRANKLINOU ROOSVELT
            "00200346",    //BANK OF CYPRUS PUBLIC COMPANY LTD PLATRES
            "00200347",    //BANK OF CYPRUS PUBLIC COMPANY LTD LIMASSOL FOREIGN OPERATIONS CENTRE
            "00200348",    //BANK OF CYPRUS PUBLIC COMPANY LTD TSIRIO
            "00200349",    //BANK OF CYPRUS PUBLIC COMPANY LTD YPSONAS
            "00200350",    //BANK OF CYPRUS PUBLIC COMPANY LTD KANIKA COMPLEX-THYRIDA
            "00200351",    //BANK OF CYPRUS PUBLIC COMPANY LTD THYRIDA AG. ZONIS
            "00200352",    //BANK OF CYPRUS PUBLIC COMPANY LTD EPISKOPI
            "00200353",    //BANK OF CYPRUS PUBLIC COMPANY LTD AYIOS ATHANASIOS
            "00200354",    //BANK OF CYPRUS PUBLIC COMPANY LTD PISSOURI
            "00200355",    //BANK OF CYPRUS PUBLIC COMPANY LTD RENANDA
            "00200356",    //BANK OF CYPRUS PUBLIC COMPANY LTD LEONDIOU
            "00200357",    //BANK OF CYPRUS PUBLIC COMPANY LTD KARMIOTISSA
            "00200358",    //BANK OF CYPRUS PUBLIC COMPANY LTD AYIA PHILA
            "00200359",    //BANK OF CYPRUS PUBLIC COMPANY LTD LONDINOU
            "00200360",    //BANK OF CYPRUS PUBLIC COMPANY LTD TRACHONI
            "00200361",    //BANK OF CYPRUS PUBLIC COMPANY LTD AMATHOUNTOS AV.
            "00200362",    //BANK OF CYPRUS PUBLIC COMPANY LTD DIMOTIKIS AGORAS
            "00200363",    //BANK OF CYPRUS PUBLIC COMPANY LTD SYN.MAKARIOU C'
            "00200364",    //BANK OF CYPRUS PUBLIC COMPANY LTD ELMAC-AMATHOUNTOS
            "00200365",    //BANK OF CYPRUS PUBLIC COMPANY LTD TAKELENA APTS
            "00200366",    //BANK OF CYPRUS PUBLIC COMPANY LTD NEO LIMANI L/SOU
            "00200367",    //BANK OF CYPRUS PUBLIC COMPANY LTD 86B AKADEMIAS
            "00200368",    //BANK OF CYPRUS PUBLIC COMPANY LTD TIFFANY BRANCH
            "00200373",    //BANK OF CYPRUS PUBLIC COMPANY LTD KAPSALOS BUSINESS CENTRE
            "00200374",    //BANK OF CYPRUS PUBLIC COMPANY LTD KENTRIKI YP. DIAX. LOGAR. PROSOPIKOU SYGROTIMATOS
            "00200375",    //BANK OF CYPRUS PUBLIC COMPANY LTD BUSINESS CENTRE L/SSOL MAIN BR
            "00200376",    //BANK OF CYPRUS PUBLIC COMPANY LTD BUSINESSCENTRE MAKARIOS AVE
            "00200377",    //BANK OF CYPRUS PUBLIC COMPANY LTD BUSINESS CENTRE LINOPETRAS
            "00200378",    //BANK OF CYPRUS PUBLIC COMPANY LTD BUSINESS CENTRE PAPHOS STR.
            "00200381",    //BANK OF CYPRUS PUBLIC COMPANY LTD CORPORATE BANKING CENTRE L/SSOL 1
            "00200382",    //BANK OF CYPRUS PUBLIC COMPANY LTD CORPORATE BANKING CENTRE L/SSOL 2
            "00200383",    //BANK OF CYPRUS PUBLIC COMPANY LTD CORPORATE BANKING CENTRE L/SSOL 3
            "00200384",    //BANK OF CYPRUS PUBLIC COMPANY LTD RECOVERIES L/SOU
            "00200385",    //BANK OF CYPRUS PUBLIC COMPANY LTD INTERNATIONAL BUSINESS UNIT
            "00200386",    //BANK OF CYPRUS PUBLIC COMPANY LTD MOLOS
            "00200388",    //BANK OF CYPRUS PUBLIC COMPANY LTD AYIOS NICOLAOS
            "00200389",    //BANK OF CYPRUS PUBLIC COMPANY LTD KATO POLEMIDIA
            "00200390",    //BANK OF CYPRUS PUBLIC COMPANY LTD NICOU PATTICHI
            "00200391",    //BANK OF CYPRUS PUBLIC COMPANY LTD 43 MISIAOULI & KAVAZOGLU
            "00200393",    //BANK OF CYPRUS PUBLIC COMPANY LTD LIMASSOL TRADE FINANCE CENTRE
            "00200394",    //BANK OF CYPRUS PUBLIC COMPANY LTD ATHINON
            "00200395",    //BANK OF CYPRUS PUBLIC COMPANY LTD CORPORATE SERVICE CENTRE
            "00200402",    //BANK OF CYPRUS PUBLIC COMPANY LTD PERNERA
            "00200403",    //BANK OF CYPRUS PUBLIC COMPANY LTD SUNRISE CASH OFFICE
            "00200440",    //BANK OF CYPRUS PUBLIC COMPANY LTD FAMAGUSTA DISTRICT
            "00200441",    //BANK OF CYPRUS PUBLIC COMPANY LTD FAMAGUSTA DISTRICT
            "00200442",    //BANK OF CYPRUS PUBLIC COMPANY LTD FAMAGUSTA DISTRICT
            "00200443",    //BANK OF CYPRUS PUBLIC COMPANY LTD FAMAGUSTA DISTRICT
            "00200444",    //BANK OF CYPRUS PUBLIC COMPANY LTD PARALIMINI MAIN BRANCH
            "00200445",    //BANK OF CYPRUS PUBLIC COMPANY LTD FAMAGUSTA DISTRICT
            "00200446",    //BANK OF CYPRUS PUBLIC COMPANY LTD FAMAGUSTA DISTRICT
            "00200447",    //BANK OF CYPRUS PUBLIC COMPANY LTD FAMAGUSTA DISTRICT
            "00200448",    //BANK OF CYPRUS PUBLIC COMPANY LTD FAMAGUSTA DISTRICT
            "00200449",    //BANK OF CYPRUS PUBLIC COMPANY LTD AYIA NAPA MAIN BRANCH
            "00200450",    //BANK OF CYPRUS PUBLIC COMPANY LTD FAMAGUSTA DISTRICT
            "00200451",    //BANK OF CYPRUS PUBLIC COMPANY LTD LIMANAKI, AG. NAPA
            "00200452",    //BANK OF CYPRUS PUBLIC COMPANY LTD LIMANAKI - CASH OFFICE
            "00200454",    //BANK OF CYPRUS PUBLIC COMPANY LTD FRENAROS
            "00200455",    //BANK OF CYPRUS PUBLIC COMPANY LTD DERYNIA
            "00200456",    //BANK OF CYPRUS PUBLIC COMPANY LTD ARCH. MAKARIOU
            "00200475",    //BANK OF CYPRUS PUBLIC COMPANY LTD BUSINESS CENTRE PARALIMNIOU
            "00200481",    //BANK OF CYPRUS PUBLIC COMPANY LTD CORPORATE BANK. AM/STOU
            "00200485",    //BANK OF CYPRUS PUBLIC COMPANY LTD SOTIRAS
            "00200487",    //BANK OF CYPRUS PUBLIC COMPANY LTD LIOPETRI
            "00200492",    //BANK OF CYPRUS PUBLIC COMPANY LTD AVGOROU
            "00200495",    //BANK OF CYPRUS PUBLIC COMPANY LTD CORPORATE SERVICE CENTRE
            "00200503",    //BANK OF CYPRUS PUBLIC COMPANY LTD KARPASIANA
            "00200516",    //BANK OF CYPRUS PUBLIC COMPANY LTD PRIVATE BANKING LARNACA
            "00200548",    //BANK OF CYPRUS PUBLIC COMPANY LTD LARNACA AIRPORT DEPARTURES- CASH OFFICE
            "00200549",    //BANK OF CYPRUS PUBLIC COMPANY LTD LARNACA AIRPORT ARRIVALS- CASH OFFICE
            "00200550",    //BANK OF CYPRUS PUBLIC COMPANY LTD LARNACA MAIN BRANCH
            "00200551",    //BANK OF CYPRUS PUBLIC COMPANY LTD ATHIENOU
            "00200552",    //BANK OF CYPRUS PUBLIC COMPANY LTD ARADIPPOU
            "00200553",    //BANK OF CYPRUS PUBLIC COMPANY LTD FANEROMENIS
            "00200554",    //BANK OF CYPRUS PUBLIC COMPANY LTD MAKARIOU
            "00200555",    //BANK OF CYPRUS PUBLIC COMPANY LTD XYLOPHAGOU
            "00200556",    //BANK OF CYPRUS PUBLIC COMPANY LTD GR AFXENTIOU
            "00200557",    //BANK OF CYPRUS PUBLIC COMPANY LTD AYIOS LAZAROS, CASH OFFICE
            "00200559",    //BANK OF CYPRUS PUBLIC COMPANY LTD ORMEDIA
            "00200560",    //BANK OF CYPRUS PUBLIC COMPANY LTD LIVADIA
            "00200561",    //BANK OF CYPRUS PUBLIC COMPANY LTD LEFKARA
            "00200562",    //BANK OF CYPRUS PUBLIC COMPANY LTD CHRYSOPOLITISSIS
            "00200563",    //BANK OF CYPRUS PUBLIC COMPANY LTD ERMOU - CASH OFFICE
            "00200564",    //BANK OF CYPRUS PUBLIC COMPANY LTD ARTEMIDOS THYRIDA
            "00200565",    //BANK OF CYPRUS PUBLIC COMPANY LTD ANGLISSIDES
            "00200566",    //BANK OF CYPRUS PUBLIC COMPANY LTD DROMOLAXIA, CASH OFFICE
            "00200567",    //BANK OF CYPRUS PUBLIC COMPANY LTD OROCLINI
            "00200568",    //BANK OF CYPRUS PUBLIC COMPANY LTD SP.KYPRIANOU
            "00200569",    //BANK OF CYPRUS PUBLIC COMPANY LTD PHANEROMENIS
            "00200570",    //BANK OF CYPRUS PUBLIC COMPANY LTD CONSNTANTINOUPOLEOS
            "00200571",    //BANK OF CYPRUS PUBLIC COMPANY LTD KAMARES
            "00200575",    //BANK OF CYPRUS PUBLIC COMPANY LTD BUSINESS CENTRE LARNACA MAIN
            "00200576",    //BANK OF CYPRUS PUBLIC COMPANY LTD BUSINESS CENTRE PHANEROMENIS,L/CA
            "00200577",    //BANK OF CYPRUS PUBLIC COMPANY LTD BUSINESS CENTRE MAKARIOU,L/CA
            "00200581",    //BANK OF CYPRUS PUBLIC COMPANY LTD CORPORATE BANKING CENTRE L/CA 1
            "00200582",    //BANK OF CYPRUS PUBLIC COMPANY LTD INTERNATIONAL BUSINESS UNIT
            "00200583",    //BANK OF CYPRUS PUBLIC COMPANY LTD LARNACA TRADE FINANCE CENTRE
            "00200584",    //BANK OF CYPRUS PUBLIC COMPANY LTD RECOVERIES L/CA
            "00200592",    //BANK OF CYPRUS PUBLIC COMPANY LTD CORPORATE SERVICE CENTRE
            "00200593",    //BANK OF CYPRUS PUBLIC COMPANY LTD KITI
            "00200595",    //BANK OF CYPRUS PUBLIC COMPANY LTD XYLOTYMPOU,
            "00200603",    //BANK OF CYPRUS PUBLIC COMPANY LTD ALIATHON
            "00200655",    //BANK OF CYPRUS PUBLIC COMPANY LTD INTERNATIONAL BUSINESS UNIT
            "00200660",    //BANK OF CYPRUS PUBLIC COMPANY LTD PAPHOS MAIN BRANCH
            "00200661",    //BANK OF CYPRUS PUBLIC COMPANY LTD POLIS CHRYSOCHOUS
            "00200662",    //BANK OF CYPRUS PUBLIC COMPANY LTD APOSTOLOS PAVLOS AVE& MORPHEAS
            "00200663",    //BANK OF CYPRUS PUBLIC COMPANY LTD KATO PYRGOS
            "00200664",    //BANK OF CYPRUS PUBLIC COMPANY LTD CORAL BAY
            "00200665",    //BANK OF CYPRUS PUBLIC COMPANY LTD LATSI
            "00200667",    //BANK OF CYPRUS PUBLIC COMPANY LTD APOSTOLOU PAVLOU & POSEID. CASH OFFICE
            "00200668",    //BANK OF CYPRUS PUBLIC COMPANY LTD PAPHIAKO
            "00200669",    //BANK OF CYPRUS PUBLIC COMPANY LTD TAFOI VASILEON
            "00200670",    //BANK OF CYPRUS PUBLIC COMPANY LTD KATO PAPHOS
            "00200671",    //BANK OF CYPRUS PUBLIC COMPANY LTD POLEMI
            "00200672",    //BANK OF CYPRUS PUBLIC COMPANY LTD NEOPHYTOU NICOLAIDES
            "00200674",    //BANK OF CYPRUS PUBLIC COMPANY LTD CHLORAKA
            "00200675",    //BANK OF CYPRUS PUBLIC COMPANY LTD PEYIA
            "00200676",    //BANK OF CYPRUS PUBLIC COMPANY LTD ZAPPIOU
            "00200677",    //BANK OF CYPRUS PUBLIC COMPANY LTD HELLAS AVE
            "00200678",    //BANK OF CYPRUS PUBLIC COMPANY LTD AKAMANTIDOS
            "00200679",    //BANK OF CYPRUS PUBLIC COMPANY LTD DANAHS
            "00200681",    //BANK OF CYPRUS PUBLIC COMPANY LTD EVEGORA PALLIKARIDE BUSINESS CENTRE
            "00200684",    //BANK OF CYPRUS PUBLIC COMPANY LTD RECOVERIES PAPHOU
            "00200685",    //BANK OF CYPRUS PUBLIC COMPANY LTD CONSTANTIAS
            "00200686",    //BANK OF CYPRUS PUBLIC COMPANY LTD EVAGOROU
            "00200690",    //BANK OF CYPRUS PUBLIC COMPANY LTD BUSINESS CENTRE PAPHOS MAIN
            "00200691",    //BANK OF CYPRUS PUBLIC COMPANY LTD BUSINESS CENTRE AKAMANTIDOS,PAPHOS
            "00200692",    //BANK OF CYPRUS PUBLIC COMPANY LTD BUSINESS CENTRE POLIS CHRYSOCHOUS
            "00200693",    //BANK OF CYPRUS PUBLIC COMPANY LTD PAPHOS TRADE FINANCE CENTRE
            "00200770",    //BANK OF CYPRUS PUBLIC COMPANY LTD KYRENIA DISTRICT
            "00200771",    //BANK OF CYPRUS PUBLIC COMPANY LTD KYRENIA DISTRICT
            "00200772",    //BANK OF CYPRUS PUBLIC COMPANY LTD KYRENIA DISTRICT
            "00200880",    //BANK OF CYPRUS PUBLIC COMPANY LTD MORPHOU DISTRICT
            "00200881",    //BANK OF CYPRUS PUBLIC COMPANY LTD MORPHOU DISTRICT
            "00200882",    //BANK OF CYPRUS PUBLIC COMPANY LTD MORPHOU DISTRICT
            "00300001",    //Bank of Cyprus Public Company Ltd Nicosia Main
            "00300002",    //Bank of Cyprus Public Company Ltd Eleftheria Square
            "00300003",    //Bank of Cyprus Public Company Ltd Pallouriotissa
            "00300004",    //Bank of Cyprus Public Company Ltd Strovolos
            "00300005",    //Bank of Cyprus Public Company Ltd Ayios Antonios
            "00300006",    //Bank of Cyprus Public Company Ltd Ayios Dhometios
            "00300007",    //Bank of Cyprus Public Company Ltd Acropolis
            "00300008",    //Bank of Cyprus Public Company Ltd Kykkos
            "00300009",    //Bank of Cyprus Public Company Ltd Lakatamia
            "00300011",    //Bank of Cyprus Public Company Ltd Ayioi Omoloyites
            "00300013",    //Bank of Cyprus Public Company Ltd Evagorou
            "00300016",    //Bank of Cyprus Public Company Ltd Aglantzia
            "00300017",    //Bank of Cyprus Public Company Ltd Athalassa
            "00300020",    //Bank of Cyprus Public Company Ltd Limassol Main
            "00300021",    //Bank of Cyprus Public Company Ltd Arch. Makarios Avenue
            "00300022",    //Bank of Cyprus Public Company Ltd Omonia Area
            "00300023",    //Bank of Cyprus Public Company Ltd Pentadromos
            "00300024",    //Bank of Cyprus Public Company Ltd Court Square
            "00300025",    //Bank of Cyprus Public Company Ltd New Port
            "00300026",    //Bank of Cyprus Public Company Ltd Academias
            "00300027",    //Bank of Cyprus Public Company Ltd Ariel
            "00300032",    //Bank of Cyprus Public Company Ltd Liopetri
            "00300033",    //Bank of Cyprus Public Company Ltd Xylophagou
            "00300034",    //Bank of Cyprus Public Company Ltd Frenaros
            "00300035",    //Bank of Cyprus Public Company Ltd Sotera
            "00300036",    //Bank of Cyprus Public Company Ltd Ayia Napa No.1
            "00300037",    //Bank of Cyprus Public Company Ltd Paralimni Main
            "00300038",    //Bank of Cyprus Public Company Ltd Avgorou
            "00300040",    //Bank of Cyprus Public Company Ltd Larnaca Main
            "00300047",    //Bank of Cyprus Public Company Ltd Aradhippou
            "00300048",    //Bank of Cyprus Public Company Ltd Stratigou Timayia
            "00300049",    //Bank of Cyprus Public Company Ltd Athienou
            "00300052",    //Bank of Cyprus Public Company Ltd Astromeritis
            "00300053",    //Bank of Cyprus Public Company Ltd Dhali
            "00300054",    //Bank of Cyprus Public Company Ltd Akaki
            "00300055",    //Bank of Cyprus Public Company Ltd Latsia
            "00300056",    //Bank of Cyprus Public Company Ltd Evrychou
            "00300057",    //Bank of Cyprus Public Company Ltd Peristerona
            "00300058",    //Bank of Cyprus Public Company Ltd Kato Deftera
            "00300059",    //Bank of Cyprus Public Company Ltd Kokkinotrimithia
            "00300060",    //Bank of Cyprus Public Company Ltd Kanaris & Votsis
            "00300061",    //Bank of Cyprus Public Company Ltd Kato Paphos No.1
            "00300062",    //Bank of Cyprus Public Company Ltd Evagora Pallikaride
            "00300063",    //Bank of Cyprus Public Company Ltd Paphos Main
            "00300065",    //Bank of Cyprus Public Company Ltd Polis Chrysochous
            "00300067",    //Bank of Cyprus Public Company Ltd Ayios Ioannis
            "00300069",    //Bank of Cyprus Public Company Ltd Pera Chorio Nisou
            "00300070",    //Bank of Cyprus Public Company Ltd Makariou Avenue
            "00300071",    //Bank of Cyprus Public Company Ltd Stasinou
            "00300073",    //Bank of Cyprus Public Company Ltd Lycavitos Avenue
            "00300075",    //Bank of Cyprus Public Company Ltd Makedonitissa
            "00300076",    //Bank of Cyprus Public Company Ltd Paliometocho
            "00300081",    //Bank of Cyprus Public Company Ltd Linopetra
            "00300082",    //Bank of Cyprus Public Company Ltd Enaerios
            "00300083",    //Bank of Cyprus Public Company Ltd Kato Polemidia
            "00300084",    //Bank of Cyprus Public Company Ltd Platres
            "00300085",    //Bank of Cyprus Public Company Ltd Ayias Phylaxis
            "00300086",    //Bank of Cyprus Public Company Ltd Protaras
            "00300087",    //Bank of Cyprus Public Company Ltd Lefkara
            "00300088",    //Bank of Cyprus Public Company Ltd Xylotymbou
            "00300090",    //Bank of Cyprus Public Company Ltd Ormidhia
            "00300092",    //Bank of Cyprus Public Company Ltd Episkopi
            "00300095",    //Bank of Cyprus Public Company Ltd Oroklini
            "00300097",    //Bank of Cyprus Public Company Ltd Artemidos
            "00300098",    //Bank of Cyprus Public Company Ltd Meneou
            "00300099",    //Bank of Cyprus Public Company Ltd Kiti
            "00300100",    //Bank of Cyprus Public Company Ltd Mosfiloti
            "00300101",    //Bank of Cyprus Public Company Ltd Strovolos Industrial Area
            "00300103",    //Bank of Cyprus Public Company Ltd Ayios Eleftherios
            "00300104",    //Bank of Cyprus Public Company Ltd Platy Area Aglantzia
            "00300110",    //Bank of Cyprus Public Company Ltd Nikis Avenue
            "00300111",    //Bank of Cyprus Public Company Ltd Anthoupolis
            "00300113",    //Bank of Cyprus Public Company Ltd Klirou
            "00300114",    //Bank of Cyprus Public Company Ltd Kennedy Avenue
            "00300118",    //Bank of Cyprus Public Company Ltd Ayios Mamas
            "00300120",    //Bank of Cyprus Public Company Ltd Pissouri
            "00300121",    //Bank of Cyprus Public Company Ltd Nikou Patichi
            "00300123",    //Bank of Cyprus Public Company Ltd Fota Symillides
            "00300126",    //Bank of Cyprus Public Company Ltd Zakaki
            "00300129",    //Bank of Cyprus Public Company Ltd Yeroskipou
            "00300130",    //Bank of Cyprus Public Company Ltd Kato Paphos No.3
            "00300158",    //Bank of Cyprus Public Company Ltd IBC Nicosia
            "00300168",    //Bank of Cyprus Public Company Ltd IBC Limassol
            "00300177",    //Bank of Cyprus Public Company Ltd IBC Larnaca
            "00300178",    //Bank of Cyprus Public Company Ltd IBC Nicosia
            "00300179",    //Bank of Cyprus Public Company Ltd IBC Limassol
            "00300341",    //Bank of Cyprus Public Company Ltd eBank
            "00300189",    //Bank of Cyprus Public Company Ltd Head Office
            "00300180",    //Bank of Cyprus Public Company Ltd Cards Services
            "00500010",    //HELLENIC BANK PUBLIC COMPANY LTD HEAD OFFICE
            "00500012",    //HELLENIC BANK PUBLIC COMPANY LTD GROUP CARD SERVICES
            "00500023",    //HELLENIC BANK PUBLIC COMPANY LTD GROUP TRUST & CUSTODIAN SERV.
            "00500026",    //HELLENIC BANK PUBLIC COMPANY LTD PRIVATE BANKING
            "00500040",    //HELLENIC BANK PUBLIC COMPANY LTD HVT & SPECIAL SITUTATIONS
            "00500041",    //HELLENIC BANK PUBLIC COMPANY LTD RECOVERIES MANAGEMENT
            "00500042",    //HELLENIC BANK PUBLIC COMPANY LTD ENFORCEMENT & RESOLUTION
            "00500043",    //HELLENIC BANK PUBLIC COMPANY LTD DRU COLLECTIONS
            "00500044",    //HELLENIC BANK PUBLIC COMPANY LTD PROPERTY MANAGEMENT UNIT
            "00500099",    //HELLENIC BANK PUBLIC COMPANY LTD STAFF CREDIT FACILITIES
            "00500101",    //HELLENIC BANK PUBLIC COMPANY LTD PLATIAS ELEFTHERIAS
            "00500102",    //HELLENIC BANK PUBLIC COMPANY LTD KOKKINOTRIMITHIAS
            "00500105",    //HELLENIC BANK PUBLIC COMPANY LTD ATHALASSAS
            "00500106",    //HELLENIC BANK PUBLIC COMPANY LTD DEMOSTHENI SEVERI
            "00500108",    //HELLENIC BANK PUBLIC COMPANY LTD  KANTARAS
            "00500109",    //HELLENIC BANK PUBLIC COMPANY LTD KENNETY
            "00500112",    //HELLENIC BANK PUBLIC COMPANY LTD AGLANTZIA
            "00500115",    //HELLENIC BANK PUBLIC COMPANY LTD 115 BUSINESS CENTRE
            "00500116",    //HELLENIC BANK PUBLIC COMPANY LTD ATHALASSA BUSINESS CENTRE
            "00500119",    //HELLENIC BANK PUBLIC COMPANY LTD NICOSIA CORPORATE CENTRE
            "00500120",    //HELLENIC BANK PUBLIC COMPANY LTD LATSIA
            "00500121",    //HELLENIC BANK PUBLIC COMPANY LTD DIGHENI AKRITA
            "00500122",    //HELLENIC BANK PUBLIC COMPANY LTD AKROPOLIS
            "00500124",    //HELLENIC BANK PUBLIC COMPANY LTD AYIOU ANTONIOU
            "00500125",    //HELLENIC BANK PUBLIC COMPANY LTD AYIOU DHOMETIOU
            "00500126",    //HELLENIC BANK PUBLIC COMPANY LTD STROVOLOU
            "00500128",    //HELLENIC BANK PUBLIC COMPANY LTD KAKOPETRIAS
            "00500131",    //HELLENIC BANK PUBLIC COMPANY LTD PRODROMOU
            "00500132",    //HELLENIC BANK PUBLIC COMPANY LTD STAVROU
            "00500133",    //HELLENIC BANK PUBLIC COMPANY LTD PLATY
            "00500134",    //HELLENIC BANK PUBLIC COMPANY LTD TSERIOU
            "00500135",    //HELLENIC BANK PUBLIC COMPANY LTD DHALIOU
            "00500137",    //HELLENIC BANK PUBLIC COMPANY LTD KATO LAKATAMIAS
            "00500139",    //HELLENIC BANK PUBLIC COMPANY LTD EGKOMIS
            "00500140",    //HELLENIC BANK PUBLIC COMPANY LTD INTERNATIONAL BUSINESS CENTRE ATHALASSAS
            "00500190",    //HELLENIC BANK PUBLIC COMPANY LTD INTERNATIONAL BUSINESS CENTRE PLATIAS ELEFTHERIAS
            "00500196",    //HELLENIC BANK PUBLIC COMPANY LTD HVT NICOSIA - LARNACA
            "00500197",    //HELLENIC BANK PUBLIC COMPANY LTD RETAIL AMU NICOSIA
            "00500198",    //HELLENIC BANK PUBLIC COMPANY LTD BUSINESS AMU NICOSIA
            "00500201",    //HELLENIC BANK PUBLIC COMPANY LTD ARCHIEPISKOPOU MAKARIOU LIMASSOL
            "00500208",    //HELLENIC BANK PUBLIC COMPANY LTD VASEON AKROTIRIOU
            "00500214",    //HELLENIC BANK PUBLIC COMPANY LTD BUSIN.CENT.GLASTONOS&ANAXAGORA
            "00500215",    //HELLENIC BANK PUBLIC COMPANY LTD MAKARIOU BUSINESS CENTRE
            "00500219",    //HELLENIC BANK PUBLIC COMPANY LTD LIMASSOL -PAPHOS CORPORATE CENTRE
            "00500239",    //HELLENIC BANK PUBLIC COMPANY LTD AYIOS GEORGIOS
            "00500240",    //HELLENIC BANK PUBLIC COMPANY LTD INTERNATIONAL BUSINESS CENTRE LIMASSOL
            "00500241",    //HELLENIC BANK PUBLIC COMPANY LTD GLADSTONOS
            "00500242",    //HELLENIC BANK PUBLIC COMPANY LTD PAPHOU
            "00500243",    //HELLENIC BANK PUBLIC COMPANY LTD PLATIAS DIKASTIRION
            "00500245",    //HELLENIC BANK PUBLIC COMPANY LTD POTAMOU GERMASOYIAS
            "00500248",    //HELLENIC BANK PUBLIC COMPANY LTD DIMOTIKIS AGORAS
            "00500250",    //HELLENIC BANK PUBLIC COMPANY LTD MESA GITONIAS
            "00500251",    //HELLENIC BANK PUBLIC COMPANY LTD FRAKLINOU ROUSVELT
            "00500253",    //HELLENIC BANK PUBLIC COMPANY LTD AYIAS FYLAS
            "00500255",    //HELLENIC BANK PUBLIC COMPANY LTD KATO POLEMIDIA
            "00500259",    //HELLENIC BANK PUBLIC COMPANY LTD AKADIMIAS
            "00500290",    //HELLENIC BANK PUBLIC COMPANY LTD SHIPPING BUSINESS CENTRE
            "00500296",    //HELLENIC BANK PUBLIC COMPANY LTD HVT LIMASSOL - PAPHOS
            "00500297",    //HELLENIC BANK PUBLIC COMPANY LTD RETAIL AMU LIMASSOL - PAPHOS
            "00500298",    //HELLENIC BANK PUBLIC COMPANY LTD BUSINESS AMU LIMASSOL - PAPHOS
            "00500301",    //HELLENIC BANK PUBLIC COMPANY LTD ZINONOS KITIEOS
            "00500305",    //HELLENIC BANK PUBLIC COMPANY LTD VASEON DHEKELIAS
            "00500314",    //HELLENIC BANK PUBLIC COMPANY LTD LARNACA BUSINESS CENTRE
            "00500319",    //HELLENIC BANK PUBLIC COMPANY LTD LARNACA-FAMAGUSTA CORPORATE CENTRE
            "00500340",    //HELLENIC BANK PUBLIC COMPANY LTD INTERNATIONAL BUSINESS CENTRE LARNACA
            "00500360",    //HELLENIC BANK PUBLIC COMPANY LTD NICOU PATTICHI
            "00500362",    //HELLENIC BANK PUBLIC COMPANY LTD ARCHIEPISKOPOU MAKARIOU
            "00500368",    //HELLENIC BANK PUBLIC COMPANY LTD SPYROU KYPRIANOY
            "00500369",    //HELLENIC BANK PUBLIC COMPANY LTD DIONISOU
            "00500371",    //HELLENIC BANK PUBLIC COMPANY LTD LIVADION
            "00500372",    //HELLENIC BANK PUBLIC COMPANY LTD KITIOU
            "00500373",    //HELLENIC BANK PUBLIC COMPANY LTD FANEROMENIS
            "00500397",    //HELLENIC BANK PUBLIC COMPANY LTD RETAIL AMU LARNACA - FAMAGUSTA
            "00500398",    //HELLENIC BANK PUBLIC COMPANY LTD BUSINESS AMU LARNACA - FAMAGUSTA
            "00500476",    //HELLENIC BANK PUBLIC COMPANY LTD ORMIDHIAS
            "00500414",    //HELLENIC BANK PUBLIC COMPANY LTD PARALIMNI BUSINESS CENTRE
            "00500419",    //HELLENIC BANK PUBLIC COMPANY LTD FAMAGUSTA CORPORATE CENTRE
            "00500478",    //HELLENIC BANK PUBLIC COMPANY LTD KAPPARIS
            "00500479",    //HELLENIC BANK PUBLIC COMPANY LTD SOTERA
            "00500482",    //HELLENIC BANK PUBLIC COMPANY LTD KENTRIKO PARALIMNIOU
            "00500483",    //HELLENIC BANK PUBLIC COMPANY LTD TEFKROU ANTHIA
            "00500484",    //HELLENIC BANK PUBLIC COMPANY LTD DHERINIAS
            "00500488",    //HELLENIC BANK PUBLIC COMPANY LTD MONASTIRAKI
            "00500501",    //HELLENIC BANK PUBLIC COMPANY LTD ELLADOS AVENUE
            "00500502",    //HELLENIC BANK PUBLIC COMPANY LTD TOMBS OF THE KINGS
            "00500503",    //HELLENIC BANK PUBLIC COMPANY LTD PEGIAS
            "00500508",    //HELLENIC BANK PUBLIC COMPANY LTD ELEFTHERIOU VENIZELOU
            "00500509",    //HELLENIC BANK PUBLIC COMPANY LTD DANAES
            "00500511",    //HELLENIC BANK PUBLIC COMPANY LTD APOSTOLOU PAVLOU
            "00500514",    //HELLENIC BANK PUBLIC COMPANY LTD PAPHOS BUSINESS CENTRE
            "00500519",    //HELLENIC BANK PUBLIC COMPANY LTD PAPHOS CORPORATE CENTRE
            "00500591",    //HELLENIC BANK PUBLIC COMPANY LTD NIKODEMOU MYLONA
            "00500592",    //HELLENIC BANK PUBLIC COMPANY LTD POLIS CHRYSOCHOUS
            "00500595",    //HELLENIC BANK PUBLIC COMPANY LTD YEROSKIPOU
            "00500597",    //HELLENIC BANK PUBLIC COMPANY LTD COURT AREA
            "00600520",    //NATIONAL BANK OF GREECE (CYPRUS) LTD NICOSIA MAIN
            "00600521",    //NATIONAL BANK OF GREECE (CYPRUS) LTD ELEFTHERIA SQ
            "00605211",    //NATIONAL BANK OF GREECE (CYPRUS) LTD ELEFTHERIA SQ
            "00600522",    //NATIONAL BANK OF GREECE (CYPRUS) LTD MORPHOU
            "00600523",    //NATIONAL BANK OF GREECE (CYPRUS) LTD NICOSIA MAIN
            "00600524",    //NATIONAL BANK OF GREECE (CYPRUS) LTD ELEFTHERIA SQ
            "00600525",    //NATIONAL BANK OF GREECE (CYPRUS) LTD NICOSIA MAIN
            "00605251",    //NATIONAL BANK OF GREECE (CYPRUS) LTD NICOSIA MAIN
            "00600526",    //NATIONAL BANK OF GREECE (CYPRUS) LTD MORPHOU
            "00605261",    //NATIONAL BANK OF GREECE (CYPRUS) LTD MORPHOU
            "00600527",    //NATIONAL BANK OF GREECE (CYPRUS) LTD ELEFTHERIA SQ
            "00605271",    //NATIONAL BANK OF GREECE (CYPRUS) LTD ELEFTHERIA SQ
            "00600528",    //NATIONAL BANK OF GREECE (CYPRUS) LTD LATSIA
            "00605281",    //NATIONAL BANK OF GREECE (CYPRUS) LTD LATSIA
            "00600529",    //NATIONAL BANK OF GREECE (CYPRUS) LTD ELEFTHERIA SQ
            "00600530",    //NATIONAL BANK OF GREECE (CYPRUS) LTD LARNACA
            "00605301",    //NATIONAL BANK OF GREECE (CYPRUS) LTD LARNACA
            "00600534",    //NATIONAL BANK OF GREECE (CYPRUS) LTD MORPHOU
            "00600535",    //NATIONAL BANK OF GREECE (CYPRUS) LTD LARNACA
            "00605351",    //NATIONAL BANK OF GREECE (CYPRUS) LTD LARNACA
            "00600531",    //NATIONAL BANK OF GREECE (CYPRUS) LTD PARALIMNI
            "00605311",    //NATIONAL BANK OF GREECE (CYPRUS) LTD PARALIMNI
            "00600532",    //NATIONAL BANK OF GREECE (CYPRUS) LTD PARALIMNI
            "00605321",    //NATIONAL BANK OF GREECE (CYPRUS) LTD PARALIMNI
            "00600536",    //NATIONAL BANK OF GREECE (CYPRUS) LTD LARNACA
            "00600537",    //NATIONAL BANK OF GREECE (CYPRUS) LTD LARNACA
            "00600540",    //NATIONAL BANK OF GREECE (CYPRUS) LTD LIMASSOL MAIN
            "00605401",    //NATIONAL BANK OF GREECE (CYPRUS) LTD LIMASSOL MAIN
            "00600541",    //NATIONAL BANK OF GREECE (CYPRUS) LTD LIMASSOL MAIN
            "00605411",    //NATIONAL BANK OF GREECE (CYPRUS) LTD LIMASSOL MAIN
            "00600542",    //NATIONAL BANK OF GREECE (CYPRUS) LTD LIMASSOL MAIN
            "00600543",    //NATIONAL BANK OF GREECE (CYPRUS) LTD KOLONAKIOU
            "00600544",    //NATIONAL BANK OF GREECE (CYPRUS) LTD LIMASSOL MAIN
            "00605441",    //NATIONAL BANK OF GREECE (CYPRUS) LTD LIMASSOL MAIN
            "00600553",    //NATIONAL BANK OF GREECE (CYPRUS) LTD KOLONAKIOU
            "00605531",    //NATIONAL BANK OF GREECE (CYPRUS) LTD KOLONAKIOU
            "00600545",    //NATIONAL BANK OF GREECE (CYPRUS) LTD PAFOS
            "00605451",    //NATIONAL BANK OF GREECE (CYPRUS) LTD PAFOS
            "00600546",    //NATIONAL BANK OF GREECE (CYPRUS) LTD PAFOS
            "00600547",    //NATIONAL BANK OF GREECE (CYPRUS) LTD PAFOS
            "00600548",    //NATIONAL BANK OF GREECE (CYPRUS) LTD LIMASSOL MAIN
            "00600549",    //NATIONAL BANK OF GREECE (CYPRUS) LTD NICOSIA IBU
            "00605491",    //NATIONAL BANK OF GREECE (CYPRUS) LTD NICOSIA IBU
            "00600550",    //NATIONAL BANK OF GREECE (CYPRUS) LTD LIMASSOL IBU
            "00605501",    //NATIONAL BANK OF GREECE (CYPRUS) LTD LIMASSOL IBU
            "00600906",    //NATIONAL BANK OF GREECE (CYPRUS) LTD HEAD OFFICE
            "00609061",    //NATIONAL BANK OF GREECE (CYPRUS) LTD HEAD OFFICE
            "00600909",    //NATIONAL BANK OF GREECE (CYPRUS) LTD HEAD OFFICE
            "00609091",    //NATIONAL BANK OF GREECE (CYPRUS) LTD HEAD OFFICE
            "00609151",    //NATIONAL BANK OF GREECE (CYPRUS) LTD HEAD OFFICE
            "00600920",    //NATIONAL BANK OF GREECE (CYPRUS) LTD HEAD OFFICE
            "00609201",    //NATIONAL BANK OF GREECE (CYPRUS) LTD HEAD OFFICE
            "00609241",    //NATIONAL BANK OF GREECE (CYPRUS) LTD HEAD OFFICE
            "00600988",    //NATIONAL BANK OF GREECE (CYPRUS) LTD HEAD OFFICE
            "00609881",    //NATIONAL BANK OF GREECE (CYPRUS) LTD HEAD OFFICE
            "00600989",    //NATIONAL BANK OF GREECE (CYPRUS) LTD HEAD OFFICE
            "00609891",    //NATIONAL BANK OF GREECE (CYPRUS) LTD HEAD OFFICE
            "00701010",    //Co-operative Central Bank Ltd HEAD OFFICE
            "00701210",    //Co-operative Central Bank Ltd CARD CENTRE
            "00702320",    //Co-operative Credit Society Troodous Ltd HEAD OFFICE
            "00702840",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00703020",    //Co-operative Savings Society Lemesou Ltd HEAD OFFICE
            "00703310",    //Co-operative Credit Society Strovolou Ltd HEAD OFFICE
            "00703430",    //Ammochostou Co-operative Savings Society Ltd HEAD OFFICE
            "00703610",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00703710",    //Telecommunications Energy and Banks' Employees Co-operative Savings Society Ltd HEAD OFFICE
            "00704210",    //Co-operative Credit Society 'Ledra' Ltd HEAD OFFICE
            "00704430",    //Allileggyis Co-operative Credit Society Ltd HEAD OFFICE
            "00704710",    //Lakatamia - Deftera Co-operative Credit Society Ltd HEAD OFFICE
            "00704930",    //Co-operative Credit Society Makrasykas, Larnacas, Famagusta District Ltd HEAD OFFICE
            "00705010",    //Cyprus Educational Cooperative Savings Society Ltd HEAD OFFICE
            "00705210",    //Co-operative Savings Society Cyprus Policemen & Army Members Ltd HEAD OFFICE
            "00705530",    //Co-operative Credit Society Kokkinochorion Ltd HEAD OFFICE
            "00705620",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00706210",    //Periferiaki Co-operative Credit Society Lefkosias Ltd HEAD OFFICE
            "00710110",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00711610",    //Co-operative Building and Savings Society of Civil Servants Ltd HEAD OFFICE
            "00701510",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00701630",    //Ammochostou Co-operative Savings Society Ltd HEAD OFFICE
            "00701730",    //Co-operative Credit Society Kokkinochorion Ltd HEAD OFFICE
            "00701830",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00701910",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00702130",    //Co-operative Credit Society Kokkinochorion Ltd HEAD OFFICE
            "00702230",    //Co-operative Credit Society Kokkinochorion Ltd HEAD OFFICE
            "00702420",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00702630",    //Co-operative Credit Society Kokkinochorion Ltd HEAD OFFICE
            "00702720",    //Co-operative Savings Society Lemesou Ltd HEAD OFFICE
            "00702920",    //Co-operative Savings Society Lemesou Ltd HEAD OFFICE
            "00703120",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00703210",    //Co-operative Credit Society 'Ledra' Ltd HEAD OFFICE
            "00703440",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00703510",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00703810",    //Telecommunications Energy and Banks' Employees Co-operative Savings Society Ltd HEAD OFFICE
            "00703910",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00704010",    //Co-operative Credit Society Strovolou Ltd HEAD OFFICE
            "00704110",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00704310",    //Co-operative Credit Society 'Ledra' Ltd HEAD OFFICE
            "00704530",    //Ammochostou Co-operative Savings Society Ltd HEAD OFFICE
            "00704610",    //Periferiaki Co-operative Credit Society Lefkosias Ltd HEAD OFFICE
            "00704810",    //Allileggyis Co-operative Credit Society Ltd HEAD OFFICE
            "00705110",    //Cyprus Educational Cooperative Savings Society Ltd HEAD OFFICE
            "00705340",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00705430",    //Co-operative Credit Society Kokkinochorion Ltd HEAD OFFICE
            "00705710",    //Periferiaki Co-operative Credit Society Lefkosias Ltd HEAD OFFICE
            "00705830",    //Co-operative Credit Society Kokkinochorion Ltd HEAD OFFICE
            "00705920",    //Co-operative Building and Savings Society of Civil Servants Ltd HEAD OFFICE
            "00706010",    //Lakatamia - Deftera Co-operative Credit Society Ltd HEAD OFFICE
            "00706310",    //Periferiaki Co-operative Credit Society Lefkosias Ltd HEAD OFFICE
            "00706430",    //Co-operative Credit Society Kokkinochorion Ltd HEAD OFFICE
            "00706540",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00706610",    //Co-operative Savings Society Cyprus Policemen & Army Members Ltd HEAD OFFICE
            "00706720",    //Co-operative Savings Society Lemesou Ltd HEAD OFFICE
            "00706830",    //Co-operative Credit Society Kokkinochorion Ltd HEAD OFFICE
            "00706910",    //Co-operative Credit Society 'Ledra' Ltd HEAD OFFICE
            "00707030",    //Co-operative Credit Society Kokkinochorion Ltd HEAD OFFICE
            "00707110",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00707210",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00707330",    //Co-operative Credit Society Makrasykas, Larnacas, Famagusta District Ltd HEAD OFFICE
            "00707420",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00707520",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00707610",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00707720",    //Co-operative Savings Society Lemesou Ltd HEAD OFFICE
            "00707810",    //Co-operative Building and Savings Society of Civil Servants Ltd HEAD OFFICE
            "00707910",    //Telecommunications Energy and Banks' Employees Co-operative Savings Society Ltd HEAD OFFICE
            "00708010",    //Co-operative Building and Savings Society of Civil Servants Ltd HEAD OFFICE
            "00708330",    //Co-operative Credit Society Makrasykas, Larnacas, Famagusta District Ltd HEAD OFFICE
            "00708410",    //Periferiaki Co-operative Credit Society Lefkosias Ltd HEAD OFFICE
            "00708510",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00708620",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00708730",    //Co-operative Building and Savings Society of Civil Servants Ltd HEAD OFFICE
            "00708840",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00708930",    //Co-operative Credit Society Makrasykas, Larnacas, Famagusta District Ltd HEAD OFFICE
            "00710210",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00710320",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00710410",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00710540",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00710610",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00710730",    //Co-operative Credit Society Makrasykas, Larnacas, Famagusta District Ltd HEAD OFFICE
            "00710830",    //Allileggyis Co-operative Credit Society Ltd HEAD OFFICE
            "00710920",    //Co-operative Credit Society Makrasykas, Larnacas, Famagusta District Ltd HEAD OFFICE
            "00711020",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00711120",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00711230",    //Co-operative Credit Society Makrasykas, Larnacas, Famagusta District Ltd HEAD OFFICE
            "00711330",    //Allileggyis Co-operative Credit Society Ltd HEAD OFFICE
            "00711430",    //Co-operative Credit Society Kokkinochorion Ltd HEAD OFFICE
            "00711730",    //Ammochostou Co-operative Savings Society Ltd HEAD OFFICE
            "00711830",    //Allileggyis Co-operative Credit Society Ltd HEAD OFFICE
            "00711910",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00712010",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00712110",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00712210",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00712320",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00712410",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00712510",    //Periferiaki Co-operative Credit Society Lefkosias Ltd HEAD OFFICE
            "00712730",    //Allileggyis Co-operative Credit Society Ltd HEAD OFFICE
            "00712810",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00712920",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00713030",    //Ammochostou Co-operative Savings Society Ltd HEAD OFFICE
            "00713140",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00713210",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00713320",    //Co-operative Savings Society Lemesou Ltd HEAD OFFICE
            "00713420",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00713510",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00713630",    //Co-operative Credit Society Makrasykas, Larnacas, Famagusta District Ltd HEAD OFFICE
            "00713730",    //Co-operative Credit Society Makrasykas, Larnacas, Famagusta District Ltd HEAD OFFICE
            "00713840",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00713920",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00714020",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00714120",    //Co-operative Building and Savings Society of Civil Servants Ltd HEAD OFFICE
            "00714220",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00714310",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00714410",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00714520",    //Co-operative Building and Savings Society of Civil Servants Ltd HEAD OFFICE
            "00714610",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00714720",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00714930",    //Allileggyis Co-operative Credit Society Ltd HEAD OFFICE
            "00715010",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00715110",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00715210",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00715330",    //Co-operative Credit Society Makrasykas, Larnacas, Famagusta District Ltd HEAD OFFICE
            "00715410",    //Co-operative Credit Society Strovolou Ltd HEAD OFFICE
            "00715510",    //Co-operative Building and Savings Society of Civil Servants Ltd HEAD OFFICE
            "00715610",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00715810",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00715910",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00716020",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00716110",    //Periferiaki Co-operative Credit Society Lefkosias Ltd HEAD OFFICE
            "00716210",    //Periferiaki Co-operative Credit Society Lefkosias Ltd HEAD OFFICE
            "00716310",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00716410",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00716510",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00716610",    //Lakatamia - Deftera Co-operative Credit Society Ltd HEAD OFFICE
            "00716810",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00716910",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00717010",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00717110",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00717210",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00717510",    //Periferiaki Co-operative Credit Society Lefkosias Ltd HEAD OFFICE
            "00717610",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00717810",    //Lakatamia - Deftera Co-operative Credit Society Ltd HEAD OFFICE
            "00717910",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00718010",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00718110",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00718210",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00718310",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00718510",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00718710",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00718810",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00718910",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00719010",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00719110",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00719510",    //Co-operative Credit Society Strovolou Ltd HEAD OFFICE
            "00719610",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00719710",    //Co-operative Credit Society Strovolou Ltd HEAD OFFICE
            "00719810",    //Periferiaki Co-operative Credit Society Lefkosias Ltd HEAD OFFICE
            "00719910",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00720210",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00720510",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00720810",    //Co-operative Savings Society Cyprus Policemen & Army Members Ltd HEAD OFFICE
            "00720910",    //Telecommunications Energy and Banks' Employees Co-operative Savings Society Ltd HEAD OFFICE
            "00721010",    //Co-operative Credit Society Makrasykas, Larnacas, Famagusta District Ltd HEAD OFFICE
            "00721110",    //Co-operative Credit Society Strovolou Ltd HEAD OFFICE
            "00721210",    //Co-operative Building and Savings Society of Civil Servants Ltd HEAD OFFICE
            "00721510",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00721720",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00721920",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00722020",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00722120",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00722220",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00722320",    //Co-operative Savings Society Lemesou Ltd HEAD OFFICE
            "00722420",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00722520",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00722620",    //Co-operative Savings Society Lemesou Ltd HEAD OFFICE
            "00722720",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00722820",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00722920",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00723020",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00723320",    //Co-operative Savings Society Lemesou Ltd HEAD OFFICE
            "00723420",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00723720",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00723820",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00723920",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00724020",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00724120",    //Co-operative Building and Savings Society of Civil Servants Ltd HEAD OFFICE
            "00724320",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00724520",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00724620",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00724720",    //Co-operative Building and Savings Society of Civil Servants Ltd HEAD OFFICE
            "00724920",    //Co-operative Savings Society Lemesou Ltd HEAD OFFICE
            "00725020",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00725120",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00725220",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00725320",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00725420",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00725620",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00725820",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00725920",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00726020",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00726120",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00726520",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00726620",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00726720",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00726820",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00727020",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00727220",    //Co-operative Savings Society Lemesou Ltd HEAD OFFICE
            "00727320",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00727420",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00727620",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00727720",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00727820",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00727920",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00728120",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00728220",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00728420",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00728620",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00728820",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00729020",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00729120",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00729220",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00729420",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00729520",    //Co-operative Savings Society Lemesou Ltd HEAD OFFICE
            "00729620",    //Co-operative Credit Society Troodous Ltd  HEAD OFFICE
            "00729830",    //Co-operative Credit Society Makrasykas, Larnacas, Famagusta District Ltd HEAD OFFICE
            "00729930",    //Co-operative Credit Society Makrasykas, Larnacas, Famagusta District Ltd HEAD OFFICE
            "00730030",    //Co-operative Credit Society Makrasykas, Larnacas, Famagusta District Ltd HEAD OFFICE
            "00730130",    //Co-operative Credit Society Kokkinochorion Ltd HEAD OFFICE
            "00730430",    //Allileggyis Co-operative Credit Society Ltd HEAD OFFICE
            "00730530",    //Co-operative Credit Society Makrasykas, Larnacas, Famagusta District Ltd HEAD OFFICE
            "00730730",    //Ammochostou Co-operative Savings Society Ltd HEAD OFFICE
            "00730930",    //Allileggyis Co-operative Credit Society Ltd HEAD OFFICE
            "00731030",    //Co-operative Credit Society Makrasykas, Larnacas, Famagusta District Ltd HEAD OFFICE
            "00731130",    //Allileggyis Co-operative Credit Society Ltd HEAD OFFICE
            "00731230",    //Tamassos Orinis and Pitsilias Cooperative Credit Society Ltd HEAD OFFICE
            "00731330",    //Co-operative Credit Society Makrasykas, Larnacas, Famagusta District Ltd HEAD OFFICE
            "00731430",    //Allileggyis Co-operative Credit Society Ltd HEAD OFFICE
            "00731530",    //Allileggyis Co-operative Credit Society Ltd HEAD OFFICE
            "00731630",    //Ammochostou Co-operative Savings Society Ltd HEAD OFFICE
            "00731730",    //Allileggyis Co-operative Credit Society Ltd HEAD OFFICE
            "00731830",    //Co-operative Credit Society Makrasykas, Larnacas, Famagusta District Ltd HEAD OFFICE
            "00731930",    //Co-operative Credit Society Makrasykas, Larnacas, Famagusta District Ltd HEAD OFFICE
            "00732140",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00732240",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00732340",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00732440",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00732540",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00732940",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00733140",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00733240",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00733340",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00733440",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00733940",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00734240",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00734340",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00734740",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00734840",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00735040",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00735140",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00735440",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00735640",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00736540",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00736640",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00737040",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00737240",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00737340",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00737540",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00737640",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00737740",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00737840",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00737940",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00738040",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00738140",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00738240",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00738340",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00738640",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00738740",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00738840",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00738940",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00739040",    //Paphos Co-operative Savings Society Ltd HEAD OFFICE
            "00739110",    //Co-operative Building and Savings Society of Civil Servants Ltd HEAD OFFICE
            "00739230",    //Co-operative Credit Society Makrasykas, Larnacas, Famagusta District Ltd HEAD OFFICE
            "00739330",    //Co-operative Credit Society Makrasykas, Larnacas, Famagusta District Ltd HEAD OFFICE
            "00739420",    //Periferiaki Co-operative Credit Society Limassol Ltd HEAD OFFICE
            "00739610",    //Co-operative Savings Society Nicosia Ltd HEAD OFFICE
            "00740110",    //Co-operative Credit Society Strovolou Ltd HEAD OFFICE
            "00790210",    //Co-operative Credit Society Strovolou Ltd HEAD OFFICE
            "00790330",    //Ammochostou Co-operative Savings Society Ltd HEAD OFFICE
            "00800026",    //PIRAEUS BANK (CYPRUS) LTD STAFF BRANCH
            "00800028",    //PIRAEUS BANK (CYPRUS) LTD WORKOUT (ACQUIRED INDIVIDUALS)
            "00800030",    //PIRAEUS BANK (CYPRUS) LTD RECOVERIES AND WORKOUTS (LEGAL)
            "00800080",    //PIRAEUS BANK (CYPRUS) LTD PRIVATE BANKING
            "00800101",    //PIRAEUS BANK (CYPRUS) LTD NICOSIA MAIN BRANCH
            "00800102",    //PIRAEUS BANK (CYPRUS) LTD AKROPOLIS BRANCH
            "00800104",    //PIRAEUS BANK (CYPRUS) LTD PLATY BRANCH
            "00800106",    //PIRAEUS BANK (CYPRUS) LTD 28TH OCTOBER BRANCH
            "00800107",    //PIRAEUS BANK (CYPRUS) LTD STROVOLOS AVENUE BRANCH
            "00800160",    //PIRAEUS BANK (CYPRUS) LTD NICOSIA BUSINESS CENTER
            "00800170",    //PIRAEUS BANK (CYPRUS) LTD NICOSIA INTERNATIONAL BUSINESS UNIT
            "00800201",    //PIRAEUS BANK (CYPRUS) LTD MAKARIOU BRANCH LIMASSOL
            "00800202",    //PIRAEUS BANK (CYPRUS) LTD KOLONAKIOU BRANCH
            "00800203",    //PIRAEUS BANK (CYPRUS) LTD AYIOS IOANNIS BRANCH
            "00800260",    //PIRAEUS BANK (CYPRUS) LTD LIMASSOL BUSINESS CENTER
            "00800270",    //PIRAEUS BANK (CYPRUS) LTD LIMASSOL INTERNATIONAL BUSINESS UNIT
            "00800301",    //PIRAEUS BANK (CYPRUS) LTD PATTICHI AVENUE BRANCH
            "00800302",    //PIRAEUS BANK (CYPRUS) LTD MAKARIOU BRANCH LARNACA
            "00800360",    //PIRAEUS BANK (CYPRUS) LTD LARNACA BUSINESS CENTER
            "00800401",    //PIRAEUS BANK (CYPRUS) LTD 1ST APRIL BRANCH
            "00800501",    //PIRAEUS BANK (CYPRUS) LTD ELLADOS AVENUE BRANCH
            "00800502",    //PIRAEUS BANK (CYPRUS) LTD KTIMATOLOGIOU BRANCH
            "00900201",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "00900202",    //Alpha Bank Cyprus Ltd NICOSIA MAIN BRANCH
            "00900203",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "00900204",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "00900205",    //Alpha Bank Cyprus Ltd ATHALASSAS BRANCH
            "00900206",    //Alpha Bank Cyprus Ltd STROVOLOS BRANCH
            "00900207",    //Alpha Bank Cyprus Ltd LATSIA BRANCH
            "00900208",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "00900209",    //Alpha Bank Cyprus Ltd MAKEDONITISSA BRANCH
            "00900210",    //Alpha Bank Cyprus Ltd STYLIANOU LENA BRANCH
            "00900211",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "00900212",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "00900213",    //Alpha Bank Cyprus Ltd KOKKINOTRIMITHIA BRANCH
            "00900515",    //Alpha Bank Cyprus Ltd LIMASSOL MAIN BRANCH
            "00900516",    //Alpha Bank Cyprus Ltd MESA YITONIA BRANCH
            "00900517",    //Alpha Bank Cyprus Ltd MAKARIOU BRANCH
            "00900518",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "00900519",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "00900520",    //Alpha Bank Cyprus Ltd OMONIA BRANCH
            "00900521",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "00900522",    //Alpha Bank Cyprus Ltd KOLONAKIOU BRANCH
            "00900430",    //Alpha Bank Cyprus Ltd LARNACA MAIN BRANCH
            "00900431",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "00900433",    //Alpha Bank Cyprus Ltd KAMARES BRANCH
            "00900434",    //Alpha Bank Cyprus Ltd STRATIGOU TIMAYIA BRANCH
            "00900435",    //Alpha Bank Cyprus Ltd MAKARIOU BRANCH
            "00900436",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "00900483",    //Alpha Bank Cyprus Ltd RETAIL INTERNATIONAL CLIENTS UNIT
            "00900760",    //Alpha Bank Cyprus Ltd PARALIMNI BRANCH
            "00900761",    //Alpha Bank Cyprus Ltd AYIA NAPA BRANCH
            "00900762",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "00900763",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "00900645",    //Alpha Bank Cyprus Ltd PAPHOS MAIN BRANCH
            "00900646",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "00900647",    //Alpha Bank Cyprus Ltd ELLADOS BRANCH
            "00900648",    //Alpha Bank Cyprus Ltd POLIS CHRYSOCHOUS BRANCH
            "00900649",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "00900650",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "00900651",    //Alpha Bank Cyprus Ltd GRIVA DIGENI BRANCH
            "00900652",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "00900653",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "00900654",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "01000453",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "01000454",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "01000455",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "01000456",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "01000457",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "01000458",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "01000459",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "01000460",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "01000461",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "01000463",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "01000464",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "01000465",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "01000501",    //Alpha Bank Cyprus Ltd HEAD OFFICE
            "01100021",    //USB BANK PLC DIGENI AKRITA
            "01100022",    //USB BANK PLC KENNEDY
            "01100023",    //USB BANK PLC STROVOLOS
            "01100024",    //USB BANK PLC PALLOURIOTISSA
            "01100025",    //USB BANK PLC MAKEDONITISSA
            "01100026",    //USB BANK PLC METOCHIOU
            "01100027",    //USB BANK PLC MAKARIOU
            "01100028",    //USB BANK PLC LATSIA
            "01100031",    //USB BANK PLC PARALIMNI
            "01100032",    //USB BANK PLC AYIA NAPA
            "01100041",    //USB BANK PLC LARNACA
            "01100042",    //USB BANK PLC DROSIA
            "01100051",    //USB BANK PLC MAKARIOU & LEONTIOU
            "01100052",    //USB BANK PLC KOLONAKI
            "01100053",    //USB BANK PLC OMONIA
            "01100054",    //USB BANK PLC VICTORY
            "01100061",    //USB BANK PLC APOSTOLOU PAVLOU
            "01100062",    //USB BANK PLC EVAGORA PALLIKARIDES
            "01100063",    //USB BANK PLC TAFOI VASILEON
            "01100064",    //USB BANK PLC POLIS CHRYSOCHOUS
            "01100012",    //USB BANK PLC IBU-NICOSIA
            "01100015",    //USB BANK PLC IBU-LIMASSOL
            "01100011",    //USB BANK PLC FINANCIAL SERVICES
            "01200021",    //SOCIETE GENERALE BANK - CYPRUS LTD ADMINISTRATION & FINANCE
            "01200022",    //SOCIETE GENERALE BANK - CYPRUS LTD NICOSIA-D. AKRITAS BRANCH
            "01200024",    //SOCIETE GENERALE BANK - CYPRUS LTD LARNACA BRANCH
            "01200026",    //SOCIETE GENERALE BANK - CYPRUS LTD LIMASSOL BRANCH
            "01200027",    //SOCIETE GENERALE BANK - CYPRUS LTD PAPHOS BRANCH
            "01200029",    //SOCIETE GENERALE BANK - CYPRUS LTD HEAD OFFICE-STAFF
            "01200002",    //SOCIETE GENERALE BANK - CYPRUS LTD RETAIL
            "01200003",    //SOCIETE GENERALE BANK - CYPRUS LTD IBU
            "01200005",    //SOCIETE GENERALE BANK - CYPRUS LTD RECOVERY
            "01200006",    //SOCIETE GENERALE BANK - CYPRUS LTD PROJECT FINANCE
            "01200010",    //SOCIETE GENERALE BANK - CYPRUS LTD HUMAN RESOURCES
            "01200000",    //SOCIETE GENERALE BANK - CYPRUS LTD HEAD OFFICE
            "01200033",    //SOCIETE GENERALE BANK - CYPRUS LTD INTERNATIONAL DESK
            "01300578",    //NATIONAL BANK OF GREECE S.A. CYPRUS BRANCH (578)
            "01305781",    //NATIONAL BANK OF GREECE S.A. CYPRUS BRANCH (578)
            "01400101",    //THE CYPRUS DEVELOPMENT BANK PUBLIC COMPANY LTD NICOSIA MAIN BRANCH
            "01400201",    //THE CYPRUS DEVELOPMENT BANK PUBLIC COMPANY LTD LIMASSOL MAIN BRANCH
            "01400801",    //THE CYPRUS DEVELOPMENT BANK PUBLIC COMPANY LTD INTERNATIONAL BANKING CENTER
            "01800001",    //EUROBANK CYPRUS LTD NICOSIA MAIN BANKING CENTER
            "01800003",    //EUROBANK CYPRUS LTD LIMASSOL KOLONAKIOU BANKING CENTER
            "01800004",    //EUROBANK CYPRUS LTD LARNACA BANKING CENTER
            "01800005",    //EUROBANK CYPRUS LTD LIMASSOL MAKARIOU BANKING CENTER
            "01800006",    //EUROBANK CYPRUS LTD NICOSIA LIMASSOL AVENUE BANKING CENTER
            "01800007",    //EUROBANK CYPRUS LTD PAPHOS BANKING CENTER
            "01800008",    //EUROBANK CYPRUS LTD ENGOMI BANKING CENTER
            "01800009",    //EUROBANK CYPRUS LTD FAMAGUSTA BANKING CENTER
            "02102510",    //HOUSING FINANCE CORPORATION NICOSIA BRANCH
            "02102510",    //HOUSING FINANCE CORPORATION LARNACA BRANCH
            "02102510",    //HOUSING FINANCE CORPORATION LIMASSOL BRANCH
            "02102510",    //HOUSING FINANCE CORPORATION PAFOS BRANCH
            "02102510",    //HOUSING FINANCE CORPORATION PARALIMNI BRANCH
            "02900000",    //ANCORIA BANK LTD HEAD OFFICE
            "02900010",    //ANCORIA BANK LTD STAFF ACCOUNTS
            "02900101",    //ANCORIA BANK LTD NICOSIA BANKING CENTRE
            "02900201",    //ANCORIA BANK LTD LIMASSOL BANKING CENTRE
            "10100022",    //BankMed s.a.l. BankMed s.a.l. - Limassol
            "10200001",    //ARAB JORDAN INVESTMENT BANK  ARAB JORDAN INVESTMENT BANK
            "10300090",    //BANK OF BEIRUT SAL  LIMASSOL BRANCH
            "10400357",    //Bank of Beirut & the Arab Countries Sal Bank of Beirut & the Arab Countries Sal
            "10500001",    //BANQUE BEMO SAL BANQUE BEMO SAL
            "10700001",    //BANQUE SBA S.A.  CYPRUS BRANCH
            "10800001",    //Barclays Bank Plc Cyprus branch
            "10900051",    //BLOM BANK SAL Cyprus Branch
            "11000950",    //BYBLOS BANK SAL BYBLOS BANK SAL - IBU - LIMASSOL
            "11200001",    //CREDIT LIBANAIS SAL HEAD OFFICE
            "11501001",    //FBME BANK LIMITED NICOSIA BRANCH
            "11501002",    //FBME BANK LIMITED LIMASOL BRANCH
            "11601507",    //FIRST INVESTMENT BANK LTD CYPRUS BRANCH
            "11800312",    //Public joint stock company AVTOVAZBANK AVTOVAZBANK Cyprus Branch
            "12000013",    //PROMSVYAZBANK PJSC PROMSVYAZBANK PJSC CYPRUS BRANCH
            "12100001",    //JORDAN KUWAIT BANK PLC JORDAN KUWAIT BANK PLC
            "12200050",    //JORDAN AHLI BANK PLC CYPRUS BRANCH
            "12400100",    //LEBANON & GULF BANK SAL CYPRUS BRANCH
            "12500000",    //PRIVATBANK COMMERCIAL BANK NICOSIA CENTRAL OFFICE
            "12566030",    //PRIVATBANK COMMERCIAL BANK LIMASSOL OFFICE N 1
            "12566050",    //PRIVATBANK COMMERCIAL BANK NICOSIA OFFICE N 1
            "12600000",    //RCB Bank LTD HEAD OFFICE
            "12600000",    //RCB Bank LTD IBC LIMASSOL 1 BRANCH
            "12600000",    //RCB Bank LTD IBC LIMISSOL 2 BRANCH
            "12600000",    //RCB Bank LTD KOLONAKIOU BRANCH
            "12600000",    //RCB Bank LTD MOLOS BRANCH
            "12600000",    //RCB Bank LTD IBC NICOSIA BRANCH
            "12600000",    //RCB Bank LTD ENGOMI BRANCH
            "12600000",    //RCB Bank LTD DASOUPOLIS BRANCH
            "12800002",    //JSC TRASTA KOMERCBANKA (LATVIA) JSC TRASTA KOMERCBANKA CYPRUS BRANCH
            "12900001",    //CENTRAL COOPERATIVE BANK PLC BULGARIA  CYPRUS BRANCH
            "13200001",    //AS EXPOBANK AS Expobank Cyprus Branch
            "13400075",    //IBL BANK S.A.L. LIMASSOL BRANCH
            "90100001",    //CSC24SEVEN.COM LIMITED HEAD OFFICE
            "90200001",    //CardPay Europe Ltd HEAD OFFICE
            "90300001",    //SEPAGA E.M.I. LIMITED SEPAGA E.M.I. LTD
    };
}