name: test

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  maven-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: maven

      - name: Test with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: |
            target
            !target/generated-sources
            !target/generated-test-sources
            !target/classes
            !target/test-classes
            !target/maven-*
